-- ============================================================
-- 001_schema.sql
-- LegalMet Verify — Core Schema
-- ============================================================
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor).
-- This creates all enums, tables, sequences, and ID-generator
-- triggers needed by the application.
-- ============================================================

-- ────────────────────────────────────────────────
-- 1. ENUMS
-- ────────────────────────────────────────────────
-- Enums restrict column values at the database level.
-- Even if the frontend is compromised, invalid values
-- cannot be inserted.

CREATE TYPE user_role AS ENUM (
  'business_owner',
  'metrology_officer',
  'gatc_user',
  'admin',
  'citizen'
);

CREATE TYPE instrument_status AS ENUM (
  'pending',
  'verified',
  'expired',
  'rejected',
  'suspended'
);

CREATE TYPE application_type AS ENUM (
  'new_verification',
  're_verification',
  'post_repair'
);

CREATE TYPE application_status AS ENUM (
  'submitted',
  'assigned',
  'scheduled',
  'inspected',
  'approved',
  'rejected'
);

CREATE TYPE inspection_result AS ENUM ('pass', 'fail');

CREATE TYPE complaint_status AS ENUM (
  'open',
  'assigned',
  'resolved',
  'rejected'
);

CREATE TYPE sync_status AS ENUM (
  'pending',
  'syncing',
  'synced',
  'conflict'
);

-- ────────────────────────────────────────────────
-- 2. PROFILES TABLE
-- ────────────────────────────────────────────────
-- Extends Supabase auth.users with application-specific fields.
-- The id column is a foreign key to auth.users.id.

CREATE TABLE profiles (
  id            uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name     text        NOT NULL,
  phone         text,
  role          user_role   NOT NULL DEFAULT 'business_owner',
  jurisdiction_state    text,
  jurisdiction_district text,
  designation   text,
  is_active     boolean     NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- Index for filtering officers by jurisdiction
CREATE INDEX idx_profiles_jurisdiction
  ON profiles (role, jurisdiction_state, jurisdiction_district);

-- ────────────────────────────────────────────────
-- 3. STATE & DISTRICT CODE LOOKUP
-- ────────────────────────────────────────────────
-- Used by the ID generator to map names to codes.
-- This is a lookup table, not editable by users.

CREATE TABLE state_codes (
  state_name text PRIMARY KEY,
  code       text NOT NULL UNIQUE
);

CREATE TABLE district_codes (
  district_name text PRIMARY KEY,
  state_name    text NOT NULL REFERENCES state_codes(state_name),
  code          text NOT NULL UNIQUE
);

-- Insert our 4 states and 10 districts
INSERT INTO state_codes (state_name, code) VALUES
  ('Haryana',         'HR'),
  ('Maharashtra',     'MH'),
  ('Karnataka',       'KA'),
  ('Uttar Pradesh',   'UP');

INSERT INTO district_codes (district_name, state_name, code) VALUES
  ('Gurugram',   'Haryana',         'GGN'),
  ('Faridabad',  'Haryana',         'FBD'),
  ('Pune',       'Maharashtra',     'PUN'),
  ('Mumbai',     'Maharashtra',     'MUM'),
  ('Bengaluru',  'Karnataka',       'BLR'),
  ('Mysuru',     'Karnataka',       'MYS'),
  ('Lucknow',    'Uttar Pradesh',   'LKN'),
  ('Varanasi',   'Uttar Pradesh',   'VNS'),
  ('Agra',       'Uttar Pradesh',   'AGR'),
  ('Noida',      'Uttar Pradesh',   'NOI');

-- ────────────────────────────────────────────────
-- 4. DIGITAL ID SEQUENCE TABLE
-- ────────────────────────────────────────────────
-- One sequence per (district, year) pair.
-- This ensures IDs like LM-IN-HR-GGN-2026-00000001 are
-- sequential within each district and year.

CREATE TABLE digital_id_sequences (
  district_code text    NOT NULL,
  year          integer NOT NULL,
  last_value    bigint  NOT NULL DEFAULT 0,
  PRIMARY KEY (district_code, year)
);

-- Same pattern for certificate numbers
CREATE TABLE certificate_no_sequences (
  district_code text    NOT NULL,
  year          integer NOT NULL,
  last_value    bigint  NOT NULL DEFAULT 0,
  PRIMARY KEY (district_code, year)
);

-- Same for application numbers
CREATE TABLE application_no_sequences (
  district_code text    NOT NULL,
  year          integer NOT NULL,
  last_value    bigint  NOT NULL DEFAULT 0,
  PRIMARY KEY (district_code, year)
);

-- Same for complaint numbers
CREATE TABLE complaint_no_sequences (
  year          integer NOT NULL,
  last_value    bigint  NOT NULL DEFAULT 0,
  PRIMARY KEY (year)
);

-- ────────────────────────────────────────────────
-- 5. INSTRUMENTS TABLE
-- ────────────────────────────────────────────────

CREATE TABLE instruments (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  digital_id           text UNIQUE,  -- generated by trigger, never by app code
  category             text        NOT NULL,
  make                 text        NOT NULL,
  model                text        NOT NULL,
  serial_no            text        NOT NULL,
  capacity             text,
  accuracy_class       text,
  manufacture_year     integer,
  owner_id             uuid        NOT NULL REFERENCES profiles(id),
  shop_name            text,
  address              text,
  district             text        NOT NULL,
  state                text        NOT NULL,
  latitude             double precision,
  longitude            double precision,
  nameplate_photo_url  text,
  status               instrument_status NOT NULL DEFAULT 'pending',
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_instruments_owner    ON instruments (owner_id);
CREATE INDEX idx_instruments_status   ON instruments (status);
CREATE INDEX idx_instruments_district ON instruments (state, district);
CREATE INDEX idx_instruments_digital  ON instruments (digital_id);

-- ────────────────────────────────────────────────
-- 6. DIGITAL ID GENERATOR FUNCTION
-- ────────────────────────────────────────────────
-- Format: LM-IN-{state_code}-{district_code}-{year}-{seq 8 digits}
-- Example: LM-IN-HR-GGN-2026-00018452
--
-- This runs as a BEFORE INSERT trigger on instruments.
-- It atomically increments the sequence (SELECT ... FOR UPDATE)
-- which prevents duplicates even under concurrent inserts.

CREATE OR REPLACE FUNCTION generate_digital_id()
RETURNS TRIGGER AS $$
DECLARE
  v_state_code    text;
  v_district_code text;
  v_year          integer;
  v_seq           bigint;
BEGIN
  -- Look up codes
  SELECT code INTO v_state_code
    FROM state_codes WHERE state_name = NEW.state;

  SELECT code INTO v_district_code
    FROM district_codes WHERE district_name = NEW.district;

  IF v_state_code IS NULL OR v_district_code IS NULL THEN
    RAISE EXCEPTION 'Unknown state "%" or district "%"', NEW.state, NEW.district;
  END IF;

  v_year := EXTRACT(YEAR FROM now());

  -- Atomically get next sequence value
  INSERT INTO digital_id_sequences (district_code, year, last_value)
    VALUES (v_district_code, v_year, 1)
    ON CONFLICT (district_code, year)
    DO UPDATE SET last_value = digital_id_sequences.last_value + 1
    RETURNING last_value INTO v_seq;

  NEW.digital_id := 'LM-IN-' || v_state_code || '-' || v_district_code
                     || '-' || v_year::text
                     || '-' || lpad(v_seq::text, 8, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_instruments_digital_id
  BEFORE INSERT ON instruments
  FOR EACH ROW
  WHEN (NEW.digital_id IS NULL)
  EXECUTE FUNCTION generate_digital_id();

-- Auto-update updated_at on instruments
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_instruments_updated_at
  BEFORE UPDATE ON instruments
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- ────────────────────────────────────────────────
-- 7. APPLICATIONS TABLE
-- ────────────────────────────────────────────────

CREATE TABLE applications (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  application_no     text UNIQUE,  -- generated by trigger
  instrument_id      uuid        NOT NULL REFERENCES instruments(id),
  applicant_id       uuid        NOT NULL REFERENCES profiles(id),
  type               application_type   NOT NULL,
  status             application_status NOT NULL DEFAULT 'submitted',
  assigned_officer_id uuid       REFERENCES profiles(id),
  scheduled_at       timestamptz,
  documents          jsonb,
  remarks            text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_applications_instrument ON applications (instrument_id);
CREATE INDEX idx_applications_applicant  ON applications (applicant_id);
CREATE INDEX idx_applications_officer    ON applications (assigned_officer_id);
CREATE INDEX idx_applications_status     ON applications (status);

-- Application number generator
-- Format: APP-{state_code}-{district_code}-{year}-{seq 6 digits}
CREATE OR REPLACE FUNCTION generate_application_no()
RETURNS TRIGGER AS $$
DECLARE
  v_district      text;
  v_state         text;
  v_state_code    text;
  v_district_code text;
  v_year          integer;
  v_seq           bigint;
BEGIN
  -- Get district/state from the linked instrument
  SELECT district, state INTO v_district, v_state
    FROM instruments WHERE id = NEW.instrument_id;

  SELECT code INTO v_state_code
    FROM state_codes WHERE state_name = v_state;
  SELECT code INTO v_district_code
    FROM district_codes WHERE district_name = v_district;

  v_year := EXTRACT(YEAR FROM now());

  INSERT INTO application_no_sequences (district_code, year, last_value)
    VALUES (v_district_code, v_year, 1)
    ON CONFLICT (district_code, year)
    DO UPDATE SET last_value = application_no_sequences.last_value + 1
    RETURNING last_value INTO v_seq;

  NEW.application_no := 'APP-' || v_state_code || '-' || v_district_code
                         || '-' || v_year::text
                         || '-' || lpad(v_seq::text, 6, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_applications_no
  BEFORE INSERT ON applications
  FOR EACH ROW
  WHEN (NEW.application_no IS NULL)
  EXECUTE FUNCTION generate_application_no();

CREATE TRIGGER trg_applications_updated_at
  BEFORE UPDATE ON applications
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- ────────────────────────────────────────────────
-- 8. INSPECTIONS TABLE
-- ────────────────────────────────────────────────

CREATE TABLE inspections (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  application_id    uuid        NOT NULL REFERENCES applications(id),
  instrument_id     uuid        NOT NULL REFERENCES instruments(id),
  officer_id        uuid        NOT NULL REFERENCES profiles(id),
  checklist         jsonb       NOT NULL DEFAULT '{}',
  readings          jsonb       NOT NULL DEFAULT '{}',
  photos            text[]      NOT NULL DEFAULT '{}',
  latitude          double precision,
  longitude         double precision,
  result            inspection_result NOT NULL,
  remarks           text,
  inspected_at      timestamptz NOT NULL DEFAULT now(),
  offline_created_at timestamptz,
  sync_status       sync_status NOT NULL DEFAULT 'synced',
  client_uuid       uuid        NOT NULL UNIQUE DEFAULT gen_random_uuid()
);

CREATE INDEX idx_inspections_application ON inspections (application_id);
CREATE INDEX idx_inspections_instrument  ON inspections (instrument_id);
CREATE INDEX idx_inspections_officer     ON inspections (officer_id);

-- ────────────────────────────────────────────────
-- 9. TEST REPORTS TABLE
-- ────────────────────────────────────────────────

CREATE TABLE test_reports (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  instrument_id   uuid        NOT NULL REFERENCES instruments(id),
  gatc_user_id    uuid        NOT NULL REFERENCES profiles(id),
  test_data       jsonb       NOT NULL DEFAULT '{}',
  report_url      text,
  result          text        NOT NULL,
  tested_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_test_reports_instrument ON test_reports (instrument_id);

-- ────────────────────────────────────────────────
-- 10. CERTIFICATES TABLE
-- ────────────────────────────────────────────────

CREATE TABLE certificates (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  certificate_no  text UNIQUE,  -- generated by trigger
  instrument_id   uuid        NOT NULL REFERENCES instruments(id),
  inspection_id   uuid        NOT NULL REFERENCES inspections(id),
  issued_by       uuid        NOT NULL REFERENCES profiles(id),
  issued_at       timestamptz NOT NULL DEFAULT now(),
  valid_till      timestamptz NOT NULL,
  pdf_url         text,
  signature_hash  text        NOT NULL,
  is_revoked      boolean     NOT NULL DEFAULT false,
  revoked_reason  text
);

CREATE INDEX idx_certificates_instrument ON certificates (instrument_id);
CREATE INDEX idx_certificates_valid_till ON certificates (valid_till);

-- Certificate number generator
-- Format: LMC-{state_code}-{district_code}-{year}-{seq 6 digits}
CREATE OR REPLACE FUNCTION generate_certificate_no()
RETURNS TRIGGER AS $$
DECLARE
  v_district      text;
  v_state         text;
  v_state_code    text;
  v_district_code text;
  v_year          integer;
  v_seq           bigint;
BEGIN
  -- Get district/state from the linked instrument
  SELECT i.district, i.state INTO v_district, v_state
    FROM instruments i WHERE i.id = NEW.instrument_id;

  SELECT code INTO v_state_code
    FROM state_codes WHERE state_name = v_state;
  SELECT code INTO v_district_code
    FROM district_codes WHERE district_name = v_district;

  v_year := EXTRACT(YEAR FROM now());

  INSERT INTO certificate_no_sequences (district_code, year, last_value)
    VALUES (v_district_code, v_year, 1)
    ON CONFLICT (district_code, year)
    DO UPDATE SET last_value = certificate_no_sequences.last_value + 1
    RETURNING last_value INTO v_seq;

  NEW.certificate_no := 'LMC-' || v_state_code || '-' || v_district_code
                         || '-' || v_year::text
                         || '-' || lpad(v_seq::text, 6, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_certificates_no
  BEFORE INSERT ON certificates
  FOR EACH ROW
  WHEN (NEW.certificate_no IS NULL)
  EXECUTE FUNCTION generate_certificate_no();

-- ────────────────────────────────────────────────
-- 11. COMPLAINTS TABLE
-- ────────────────────────────────────────────────

CREATE TABLE complaints (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  complaint_no        text UNIQUE,  -- generated by trigger
  instrument_id       uuid        NOT NULL REFERENCES instruments(id),
  citizen_name        text        NOT NULL,
  citizen_contact     text,
  description         text        NOT NULL,
  photo_url           text,
  status              complaint_status NOT NULL DEFAULT 'open',
  assigned_officer_id uuid        REFERENCES profiles(id),
  resolution_remarks  text,
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_complaints_instrument ON complaints (instrument_id);
CREATE INDEX idx_complaints_officer    ON complaints (assigned_officer_id);
CREATE INDEX idx_complaints_status     ON complaints (status);

-- Complaint number generator
-- Format: CMP-{year}-{seq 6 digits}
CREATE OR REPLACE FUNCTION generate_complaint_no()
RETURNS TRIGGER AS $$
DECLARE
  v_year integer;
  v_seq  bigint;
BEGIN
  v_year := EXTRACT(YEAR FROM now());

  INSERT INTO complaint_no_sequences (year, last_value)
    VALUES (v_year, 1)
    ON CONFLICT (year)
    DO UPDATE SET last_value = complaint_no_sequences.last_value + 1
    RETURNING last_value INTO v_seq;

  NEW.complaint_no := 'CMP-' || v_year::text || '-' || lpad(v_seq::text, 6, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_complaints_no
  BEFORE INSERT ON complaints
  FOR EACH ROW
  WHEN (NEW.complaint_no IS NULL)
  EXECUTE FUNCTION generate_complaint_no();

-- ────────────────────────────────────────────────
-- 12. OWNERSHIP HISTORY TABLE
-- ────────────────────────────────────────────────

CREATE TABLE ownership_history (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  instrument_id   uuid        NOT NULL REFERENCES instruments(id),
  from_owner_id   uuid        REFERENCES profiles(id),
  to_owner_id     uuid        NOT NULL REFERENCES profiles(id),
  transferred_at  timestamptz NOT NULL DEFAULT now(),
  remarks         text
);

CREATE INDEX idx_ownership_instrument ON ownership_history (instrument_id);

-- ────────────────────────────────────────────────
-- 13. AUDIT LOG TABLE
-- ────────────────────────────────────────────────
-- Written ONLY by database triggers — never by application code.
-- This is the "complete digital audit trail" our presentation claims.

CREATE TABLE audit_log (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type text        NOT NULL,  -- e.g. 'instrument', 'application'
  entity_id   uuid        NOT NULL,
  action      text        NOT NULL,  -- 'INSERT', 'UPDATE', 'DELETE'
  actor_id    uuid,                  -- auth.uid() at the time
  before      jsonb,                 -- old row as JSON (NULL on INSERT)
  after       jsonb,                 -- new row as JSON (NULL on DELETE)
  ip_address  text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_entity ON audit_log (entity_type, entity_id);
CREATE INDEX idx_audit_actor  ON audit_log (actor_id);
CREATE INDEX idx_audit_time   ON audit_log (created_at DESC);

-- ────────────────────────────────────────────────
-- 14. NOTIFICATIONS TABLE
-- ────────────────────────────────────────────────
-- For expiry alerts and system notifications.

CREATE TABLE notifications (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid        NOT NULL REFERENCES profiles(id),
  title       text        NOT NULL,
  message     text        NOT NULL,
  type        text        NOT NULL DEFAULT 'info', -- info, warning, alert
  is_read     boolean     NOT NULL DEFAULT false,
  link        text,       -- optional deep link (e.g. /instruments/abc)
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_user ON notifications (user_id, is_read, created_at DESC);
